### ISSUE TITLE
(Veileder) Livssyklusen til omgrep (gyldighetsperiode.adoc)

### ISSUE THREAD

**Issue by OleVaage** [Informasjonsforvaltning/veileder-begrepsbeskrivelser#1]
Det er eit behov for nokre retningslinjer for endringar av omgrepsbeskrivingar gjennomført av omgrepsansvarleg.  Kva slags endringar i omgrepsbeskrivingane vil innebere at omgrepet vert avløyst av eit nytt omgrep? Dette vil ha konsekvensar for versjonering i tekniske løysingar som t.d. Felles omgrepskatalog.

**Comment by jimjyang** [comment]
På arbeidsgruppemøtet den 15. februar 2023 ble det konkludert med at vi ikke trengte en egen veileder ved siden av [Termlosen](https://data.norge.no/specification/termlosen) og den reviderte [Forvaltningsstandard for begrepsbeskrivelser (SKOS-AP-NO-Begrep)](https://data.norge.no/specification/skos-ap-no-begrep). 

Denne veilederen utgår og blir derfor ikke viderevedlikeholdt. Dette issuet blir heller ikke håndtert.
