### ISSUE TITLE
[publisering] PDF-filnavnet bør gjenspeile veilederens navn

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/veileder-begrepsbeskrivelser#6]
Navnet til PDF-filen som kan lastes ned er nå "document.pdf". 

Ønsker å ha et filnavn som gjenspeile veilederens navn, f.eks. repo-navnet (som også brukes i URLen til den gjeldende versjonen på data.norge.no).

**Comment by stigbd** [comment]
Realisert i d2bb5363412b77bca2d4f81c64883675f90caa69

**Comment by jimjyang** [comment]
Fiksa
